'use client';

// ═══════════════════════════════════════════════════════════════════════
// JourneyView — renders the 12-day journey computed by src/lib/journey.ts
// Shared by /track and /track/[token]. Pure presentation; the honest
// "estimated / no new scan" framing comes straight from the engine.
// ═══════════════════════════════════════════════════════════════════════

import {
  ClipboardCheck, Cog, PackageCheck, Truck, Navigation, MapPin,
  Building2, Bike, CheckCircle, Info, AlertTriangle, XCircle,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export interface JourneyStageView {
  key: string;
  label: string;
  status: string;
  icon: string;
  estimated: boolean;
  state: 'done' | 'current' | 'upcoming';
}
export interface JourneyNotice {
  level: 'info' | 'warn' | 'success' | 'error';
  title: string;
  body: string;
}
export interface JourneyEvent {
  key: string;
  title: string;
  location: string;
  timeISO: string;
}
export interface Journey {
  mode: 'normal' | 'cancelled' | 'rto' | 'failed';
  currentIndex: number;
  currentLabel: string;
  stages: JourneyStageView[];
  events: JourneyEvent[];
  ageDays: number;
  delivered: boolean;
  deliveredEstimated: boolean;
  eta: string | null;
  etaEstimated: boolean;
  lastCheckedISO: string;
  notice: JourneyNotice | null;
}

const ICONS: Record<string, LucideIcon> = {
  ClipboardCheck, Cog, PackageCheck, Truck, Navigation, MapPin, Building2, Bike, CheckCircle,
};

const NOTICE_STYLE: Record<JourneyNotice['level'], { bg: string; border: string; color: string; Icon: LucideIcon }> = {
  info:    { bg: '#EFF6FF', border: '#BFDBFE', color: '#1D4ED8', Icon: Info },
  warn:    { bg: '#FFF7ED', border: '#FED7AA', color: '#C2410C', Icon: AlertTriangle },
  success: { bg: '#F0FDF4', border: '#BBF7D0', color: '#15803D', Icon: CheckCircle },
  error:   { bg: '#FEF2F2', border: '#FECACA', color: '#DC2626', Icon: XCircle },
};

function fmtEta(iso: string) {
  return new Date(iso).toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'short', year: 'numeric' });
}

export function JourneyNoticeBanner({ journey }: { journey: Journey }) {
  if (!journey.notice) return null;
  const s = NOTICE_STYLE[journey.notice.level];
  const { Icon } = s;
  return (
    <div style={{ background: s.bg, border: `1px solid ${s.border}`, borderRadius: 12, padding: '14px 16px', display: 'flex', gap: 12, alignItems: 'flex-start' }}>
      <div style={{ color: s.color, flexShrink: 0, marginTop: 1 }}><Icon size={18} /></div>
      <div>
        <div style={{ fontSize: 14, fontWeight: 700, color: s.color, marginBottom: 2 }}>{journey.notice.title}</div>
        <div style={{ fontSize: 13, color: '#475569', lineHeight: 1.5 }}>{journey.notice.body}</div>
      </div>
    </div>
  );
}

export function JourneyEta({ journey }: { journey: Journey }) {
  if (!journey.eta || journey.delivered) return null;
  return (
    <div className="st-card">
      <p style={{ margin: '0 0 6px', fontSize: 13, color: '#64748B', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.5px' }}>
        {journey.etaEstimated ? 'Estimated Delivery by' : 'Expected Delivery by'}
      </p>
      <p style={{ margin: 0, fontSize: 22, fontWeight: 800, color: '#0F172A' }}>{fmtEta(journey.eta)}</p>
    </div>
  );
}

/** Customer-facing "Recent Activities" feed, generated by the engine. */
export function JourneyActivity({ journey }: { journey: Journey }) {
  const events = [...journey.events].reverse(); // newest first
  const fmt = (iso: string) => {
    const d = new Date(iso);
    return {
      date: d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short' }),
      time: d.toLocaleTimeString('en-IN', { hour: 'numeric', minute: '2-digit', hour12: true }),
    };
  };
  if (events.length === 0) {
    return <p style={{ fontSize: 14, color: '#94A3B8', margin: 0 }}>No activity yet — updates will appear here.</p>;
  }
  return (
    <>
      {events.map((e, i) => {
        const { date, time } = fmt(e.timeISO);
        const isLatest = i === 0;
        const isLast = i === events.length - 1;
        return (
          <div key={e.key} style={{ display: 'flex', gap: 14 }}>
            <div style={{ width: 70, flexShrink: 0, textAlign: 'right', paddingTop: 2 }}>
              <div style={{ fontSize: 14, fontWeight: 700, color: '#0F172A' }}>{date}</div>
              <div style={{ fontSize: 12, color: '#64748B', marginTop: 1 }}>{time}</div>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', flexShrink: 0 }}>
              <div style={{
                width: 10, height: 10, borderRadius: '50%',
                background: isLatest ? '#22C55E' : '#1E293B', marginTop: 6, zIndex: 10,
                boxShadow: isLatest ? '0 0 0 3px rgba(34,197,94,0.2)' : 'none',
              }} />
              {!isLast && <div style={{ width: 2, flex: 1, background: '#E2E8F0', minHeight: 36, margin: '4px 0' }} />}
            </div>
            <div style={{ paddingBottom: 20, flex: 1 }}>
              <div style={{ fontSize: 14, fontWeight: 600, color: '#1E293B', lineHeight: 1.4 }}>{e.title}</div>
              {e.location && <div style={{ fontSize: 12, color: '#64748B', marginTop: 2 }}>{e.location}</div>}
            </div>
          </div>
        );
      })}
    </>
  );
}

/** The full vertical/horizontal stepper for the canonical journey. */
export function JourneyStepper({ journey }: { journey: Journey }) {
  const stages = journey.stages;

  const renderNode = (st: JourneyStageView, size: number) => {
    const Icon = ICONS[st.icon] || Truck;
    const active = st.state === 'done' || st.state === 'current';
    const isCurrent = st.state === 'current';
    return (
      <div style={{
        width: size, height: size, borderRadius: '50%', background: '#FFFFFF',
        border: `2px solid ${active ? '#1E293B' : '#CBD5E1'}`,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        boxShadow: isCurrent ? '0 0 0 4px rgba(249,115,22,0.15)' : '0 2px 4px rgba(0,0,0,0.05)',
        color: active ? '#F97316' : '#94A3B8', zIndex: 10,
      }}>
        <Icon size={size * 0.42} strokeWidth={1.75} />
      </div>
    );
  };

  const label = (st: JourneyStageView) => {
    const active = st.state === 'done' || st.state === 'current';
    return (
      <span style={{ fontSize: 13, fontWeight: active ? 600 : 500, color: active ? '#1E293B' : '#94A3B8', lineHeight: 1.35 }}>{st.label}</span>
    );
  };

  return (
    <div className="st-card" style={{ padding: '32px 24px' }}>
      {/* Desktop */}
      <div className="jv-desktop">
        <div className="jv-desktop-row">
          {stages.map((st, idx) => (
            <div key={st.key} className={`jv-step ${st.state === 'done' ? 'completed' : ''}`}>
              {renderNode(st, 50)}
              <div style={{ marginTop: 10, textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 2 }}>{label(st)}</div>
            </div>
          ))}
        </div>
      </div>
      {/* Mobile */}
      <div className="jv-mobile">
        {stages.map((st) => (
          <div key={st.key} className={`jv-mstep ${st.state === 'done' ? 'completed' : ''}`}>
            {renderNode(st, 42)}
            <div style={{ paddingTop: 8, display: 'flex', flexDirection: 'column', gap: 2 }}>{label(st)}</div>
          </div>
        ))}
      </div>

      <style>{`
        .jv-desktop { display: block; }
        .jv-mobile { display: none; }
        .jv-desktop-row { display: flex; justify-content: space-between; position: relative; }
        .jv-step { position: relative; display: flex; flex-direction: column; align-items: center; flex: 1; }
        .jv-step::after { content:''; position:absolute; top:25px; left:50%; width:100%; height:4px; background:#E2E8F0; z-index:1; }
        .jv-step:last-child::after { display:none; }
        .jv-step.completed::after { background:#1E293B; }
        .jv-mstep { display:flex; gap:16px; position:relative; padding-bottom:22px; }
        .jv-mstep:last-child { padding-bottom:0; }
        .jv-mstep::after { content:''; position:absolute; top:42px; left:20px; width:2px; height:calc(100% - 42px); background:#CBD5E1; z-index:1; }
        .jv-mstep:last-child::after { display:none; }
        .jv-mstep.completed::after { background:#1E293B; }
        @media (max-width: 768px) {
          .jv-desktop { display:none; }
          .jv-mobile { display:block; }
        }
      `}</style>
    </div>
  );
}
